import type { AVPlaybackSource } from 'expo-av';

/** Requires statiques — chemins relatifs pour Metro (dossier assets/sounds/frets). */
export const FRET_SOUND_MODULES: Record<string, AVPlaybackSource> = {
  '1_0': require('../../../assets/sounds/frets/1_0.mp3'),
  '1_1': require('../../../assets/sounds/frets/1_1.mp3'),
  '1_2': require('../../../assets/sounds/frets/1_2.mp3'),
  '1_3': require('../../../assets/sounds/frets/1_3.mp3'),
  '1_4': require('../../../assets/sounds/frets/1_4.mp3'),
  '1_5': require('../../../assets/sounds/frets/1_5.mp3'),
  '1_6': require('../../../assets/sounds/frets/1_6.mp3'),
  '1_7': require('../../../assets/sounds/frets/1_7.mp3'),
  '1_8': require('../../../assets/sounds/frets/1_8.mp3'),
  '1_9': require('../../../assets/sounds/frets/1_9.mp3'),
  '1_10': require('../../../assets/sounds/frets/1_10.mp3'),
  '1_11': require('../../../assets/sounds/frets/1_11.mp3'),
  '1_12': require('../../../assets/sounds/frets/1_12.mp3'),
  '2_0': require('../../../assets/sounds/frets/2_0.mp3'),
  '2_1': require('../../../assets/sounds/frets/2_1.mp3'),
  '2_2': require('../../../assets/sounds/frets/2_2.mp3'),
  '2_3': require('../../../assets/sounds/frets/2_3.mp3'),
  '2_4': require('../../../assets/sounds/frets/2_4.mp3'),
  '2_5': require('../../../assets/sounds/frets/2_5.mp3'),
  '2_6': require('../../../assets/sounds/frets/2_6.mp3'),
  '2_7': require('../../../assets/sounds/frets/2_7.mp3'),
  '2_8': require('../../../assets/sounds/frets/2_8.mp3'),
  '2_9': require('../../../assets/sounds/frets/2_9.mp3'),
  '2_10': require('../../../assets/sounds/frets/2_10.mp3'),
  '2_11': require('../../../assets/sounds/frets/2_11.mp3'),
  '2_12': require('../../../assets/sounds/frets/2_12.mp3'),
  '3_0': require('../../../assets/sounds/frets/3_0.mp3'),
  '3_1': require('../../../assets/sounds/frets/3_1.mp3'),
  '3_2': require('../../../assets/sounds/frets/3_2.mp3'),
  '3_3': require('../../../assets/sounds/frets/3_3.mp3'),
  '3_4': require('../../../assets/sounds/frets/3_4.mp3'),
  '3_5': require('../../../assets/sounds/frets/3_5.mp3'),
  '3_6': require('../../../assets/sounds/frets/3_6.mp3'),
  '3_7': require('../../../assets/sounds/frets/3_7.mp3'),
  '3_8': require('../../../assets/sounds/frets/3_8.mp3'),
  '3_9': require('../../../assets/sounds/frets/3_9.mp3'),
  '3_10': require('../../../assets/sounds/frets/3_10.mp3'),
  '3_11': require('../../../assets/sounds/frets/3_11.mp3'),
  '3_12': require('../../../assets/sounds/frets/3_12.mp3'),
  '4_0': require('../../../assets/sounds/frets/4_0.mp3'),
  '4_1': require('../../../assets/sounds/frets/4_1.mp3'),
  '4_2': require('../../../assets/sounds/frets/4_2.mp3'),
  '4_3': require('../../../assets/sounds/frets/4_3.mp3'),
  '4_4': require('../../../assets/sounds/frets/4_4.mp3'),
  '4_5': require('../../../assets/sounds/frets/4_5.mp3'),
  '4_6': require('../../../assets/sounds/frets/4_6.mp3'),
  '4_7': require('../../../assets/sounds/frets/4_7.mp3'),
  '4_8': require('../../../assets/sounds/frets/4_8.mp3'),
  '4_9': require('../../../assets/sounds/frets/4_9.mp3'),
  '4_10': require('../../../assets/sounds/frets/4_10.mp3'),
  '4_11': require('../../../assets/sounds/frets/4_11.mp3'),
  '4_12': require('../../../assets/sounds/frets/4_12.mp3'),
};
